"""Winthor automation package exports."""
from .winthor_address_updater import (
    Address,
    ClientRecord,
    DEFAULT_BATCH_SIZE,
    DEFAULT_INTERVAL_HOURS,
    LOG_DIRECTORY,
    RECEITA_FEDERAL_CNPJ_ENDPOINT,
    ReceitaFederalClient,
    WinthorDatabase,
    build_logger,
    load_credentials_from_env,
    main,
    needs_update,
    normalize_address,
    parse_args,
    run_batch,
    run_orchestration,
    summarize_execution,
)

__all__ = [
    "Address",
    "ClientRecord",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_INTERVAL_HOURS",
    "LOG_DIRECTORY",
    "RECEITA_FEDERAL_CNPJ_ENDPOINT",
    "ReceitaFederalClient",
    "WinthorDatabase",
    "build_logger",
    "load_credentials_from_env",
    "main",
    "needs_update",
    "normalize_address",
    "parse_args",
    "run_batch",
    "run_orchestration",
    "summarize_execution",
]
